#!/bin/bash
#convert list of accession numbers to Taxonomy

cat Acc.list | while IFS= read -r line || [[ -n $line ]]; do echo $line > acc/$line; done

for i in *; do esearch -db nuccore -query "$i" | elink -target taxonomy | efetch -format native -mode xml | grep ScientificName | awk -F ">|<" 'BEGIN{ORS=", ";}{print $3;}' | awk -v a="$i" -F "\t" '{print a "\t" $1}' >> out.txt; done

#for taxanomic node
for i in *; do esearch -db nuccore -query "$i" | elink -target taxonomy | efetch -format docsum |xtract -pattern DocumentSummary -element Caption,TaxId| awk -v a=">""$i" -F "\t" '{print a "\t" $1}' ; done

#same as above but might be faster - need to past accesiobn numbers afterwards, possilby could pipe it.
cat acc.list | epost -db nuccore | elink -target taxonomy | efetch -format docsum |xtract -pattern DocumentSummary -element Caption,TaxId >> tax.out

#try |grep Lineage| instead

#for lca script in pipeline use:
cat acc.list | epost -db nuccore | esummary -db nuccore | xtract -pattern DocumentSummary -element AccessionVersion,TaxId >> tax.out
